name = "MiraiBots"
uuid = "e34416ce-79ee-4ebd-8d29-74bfd0620ce8"
authors = ["melonedo <44501064+melonedo@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
